$filePath = "d:\gchc\backend\src\main\java\com\example\gchc\config\DatabaseMigration.java"

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('package com.example.gchc.config;')
$lines.Add('')
$lines.Add('import lombok.extern.slf4j.Slf4j;')
$lines.Add('import org.springframework.boot.CommandLineRunner;')
$lines.Add('import org.springframework.core.annotation.Order;')
$lines.Add('import org.springframework.jdbc.core.JdbcTemplate;')
$lines.Add('import org.springframework.stereotype.Component;')
$lines.Add('')
$lines.Add('/**')
$lines.Add(' * 数据库迁移 - 在应用启动时自动执行表结构变更')
$lines.Add(' */')
$lines.Add('@Component')
$lines.Add('@Order(0)')
$lines.Add('@Slf4j')
$lines.Add('public class DatabaseMigration implements CommandLineRunner {')
$lines.Add('')
$lines.Add('    private final JdbcTemplate jdbcTemplate;')
$lines.Add('')
$lines.Add('    public DatabaseMigration(JdbcTemplate jdbcTemplate) {')
$lines.Add('        this.jdbcTemplate = jdbcTemplate;')
$lines.Add('    }')
$lines.Add('')
$lines.Add('    @Override')
$lines.Add('    public void run(String... args) {')
$lines.Add('        try {')
$lines.Add('            // 检查是否存在 code 列，如果存在则迁移到 image_url')
$lines.Add('            Integer iconCodeCount = jdbcTemplate.queryForObject(')
$lines.Add('                "SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = ''icons'' AND COLUMN_NAME = ''code''",')
$lines.Add('                Integer.class')
$lines.Add('            );')
$lines.Add('            if (iconCodeCount != null && iconCodeCount > 0) {')
$lines.Add('                log.info("开始迁移 icons 表：code -> image_url");')
$lines.Add('                // 先删除旧数据，因为emoji编码已不可用')
$lines.Add('                jdbcTemplate.execute("TRUNCATE TABLE icons");')
$lines.Add('                // 删除旧唯一索引')
$lines.Add('                try {')
$lines.Add('                    jdbcTemplate.execute("ALTER TABLE icons DROP INDEX uk_icons_code");')
$lines.Add('                } catch (Exception ignored) {')
$lines.Add('                    // 索引可能不存在，忽略')
$lines.Add('                }')
$lines.Add('                // 修改列名和类型')
$lines.Add('                jdbcTemplate.execute("ALTER TABLE icons CHANGE COLUMN code image_url VARCHAR(500) NOT NULL");')
$lines.Add('                // 添加新唯一索引')
$lines.Add('                jdbcTemplate.execute("ALTER TABLE icons ADD UNIQUE KEY uk_icons_image_url (image_url)");')
$lines.Add('                log.info("icons 表迁移完成");')
$lines.Add('            }')
$lines.Add('        } catch (Exception e) {')
$lines.Add('            log.warn("数据库迁移（icons表）跳过或失败: {}", e.getMessage());')
$lines.Add('        }')
$lines.Add('')
$lines.Add('        try {')
$lines.Add('            // 检查 milestones 表是否已有 title 列')
$lines.Add('            Integer titleCount = jdbcTemplate.queryForObject(')
$lines.Add('                "SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = ''milestones'' AND COLUMN_NAME = ''title''",')
$lines.Add('                Integer.class')
$lines.Add('            );')
$lines.Add('            if (titleCount != null && titleCount == 0) {')
$lines.Add('                log.info("开始迁移 milestones 表：添加 title 列");')
$lines.Add('                // 添加 title 列')
$lines.Add('                jdbcTemplate.execute("ALTER TABLE milestones ADD COLUMN title VARCHAR(100) NOT NULL DEFAULT '''' AFTER year");')
$lines.Add('                // 将旧的 year 值复制到 title（旧 year 作为标题）')
$lines.Add('                jdbcTemplate.execute("UPDATE milestones SET title = year");')
$lines.Add('                // 清空 year 列，让用户重新填写年份')
$lines.Add('                jdbcTemplate.execute("UPDATE milestones SET year = ''''");')
$lines.Add('                log.info("milestones 表迁移完成：year 改为年份，原 year 值已移至 title");')
$lines.Add('            }')
$lines.Add('        } catch (Exception e) {')
$lines.Add('            log.warn("数据库迁移（milestones表）跳过或失败: {}", e.getMessage());')
$lines.Add('        }')
$lines.Add('')
$lines.Add('        try {')
$lines.Add('            // 修改 carousels 表 title 列为允许 NULL')
$lines.Add('            jdbcTemplate.execute("ALTER TABLE carousels MODIFY COLUMN title VARCHAR(255) NULL");')
$lines.Add('            log.info("carousels 表 title 列已修改为允许 NULL");')
$lines.Add('        } catch (Exception e) {')
$lines.Add('            log.warn("数据库迁移（carousels表）跳过或失败: {}", e.getMessage());')
$lines.Add('        }')
$lines.Add('')
$lines.Add('        try {')
$lines.Add('            // 检查 news_categories 表是否已存在')
$lines.Add('            Integer newsCategoryTableCount = jdbcTemplate.queryForObject(')
$lines.Add('                "SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = ''news_categories''",')
$lines.Add('                Integer.class')
$lines.Add('            );')
$lines.Add('            if (newsCategoryTableCount != null && newsCategoryTableCount == 0) {')
$lines.Add('                log.info("开始创建 news_categories 表");')
$lines.Add('                jdbcTemplate.execute(')
$lines.Add('                    "CREATE TABLE IF NOT EXISTS news_categories (" +')
$lines.Add('                    "id BIGINT AUTO_INCREMENT PRIMARY KEY, " +')
$lines.Add('                    "name VARCHAR(100) NOT NULL, " +')
$lines.Add('                    "description VARCHAR(255) NULL, " +')
$lines.Add('                    "sort_order INT NOT NULL DEFAULT 0, " +')
$lines.Add('                    "enabled TINYINT(1) NOT NULL DEFAULT 1, " +')
$lines.Add('                    "created_at DATETIME(6) NULL, " +')
$lines.Add('                    "updated_at DATETIME(6) NULL, " +')
$lines.Add('                    "UNIQUE KEY uk_news_categories_name (name)" +')
$lines.Add('                    ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci"')
$lines.Add('                );')
$lines.Add('                jdbcTemplate.update(')
$lines.Add('                    "INSERT INTO news_categories (name, sort_order, enabled, created_at, updated_at) VALUES (?, ?, 1, NOW(), NOW())",')
$lines.Add('                    "公司新闻", 1')
$lines.Add('                );')
$lines.Add('                jdbcTemplate.update(')
$lines.Add('                    "INSERT INTO news_categories (name, sort_order, enabled, created_at, updated_at) VALUES (?, ?, 1, NOW(), NOW())",')
$lines.Add('                    "行业资讯", 2')
$lines.Add('                );')
$lines.Add('                jdbcTemplate.update(')
$lines.Add('                    "INSERT INTO news_categories (name, sort_order, enabled, created_at, updated_at) VALUES (?, ?, 1, NOW(), NOW())",')
$lines.Add('                    "技术分享", 3')
$lines.Add('                );')
$lines.Add('                log.info("news_categories 表创建完成，默认分类已插入");')
$lines.Add('            }')
$lines.Add('        } catch (Exception e) {')
$lines.Add('            log.warn("数据库迁移（news_categories表）跳过或失败: {}", e.getMessage());')
$lines.Add('        }')
$lines.Add('')
$lines.Add('        try {')
$lines.Add('            // 检查 users 表是否已有 avatar 列')
$lines.Add('            Integer avatarCount = jdbcTemplate.queryForObject(')
$lines.Add('                "SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = ''users'' AND COLUMN_NAME = ''avatar''",')
$lines.Add('                Integer.class')
$lines.Add('            );')
$lines.Add('            if (avatarCount != null && avatarCount == 0) {')
$lines.Add('                log.info("开始迁移 users 表：添加 avatar 列");')
$lines.Add('                jdbcTemplate.execute("ALTER TABLE users ADD COLUMN avatar VARCHAR(500) NULL AFTER phone");')
$lines.Add('                log.info("users 表 avatar 列添加完成");')
$lines.Add('            }')
$lines.Add('        } catch (Exception e) {')
$lines.Add('            log.warn("数据库迁移（users表avatar列）跳过或失败: {}", e.getMessage());')
$lines.Add('        }')
$lines.Add('')
$lines.Add('        try {')
$lines.Add('            // 检查 messages 表是否已存在')
$lines.Add('            Integer messagesTableCount = jdbcTemplate.queryForObject(')
$lines.Add('                "SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = ''messages''",')
$lines.Add('                Integer.class')
$lines.Add('            );')
$lines.Add('            if (messagesTableCount != null && messagesTableCount == 0) {')
$lines.Add('                log.info("开始创建 messages 表");')
$lines.Add('                jdbcTemplate.execute(')
$lines.Add('                    "CREATE TABLE IF NOT EXISTS messages (" +')
$lines.Add('                    "id BIGINT NOT NULL AUTO_INCREMENT, " +')
$lines.Add('                    "name VARCHAR(100) NOT NULL, " +')
$lines.Add('                    "email VARCHAR(100) NOT NULL, " +')
$lines.Add('                    "phone VARCHAR(20) NULL, " +')
$lines.Add('                    "message TEXT NOT NULL, " +')
$lines.Add('                    "replied TINYINT(1) NOT NULL DEFAULT 0, " +')
$lines.Add('                    "created_at DATETIME(6) NULL, " +')
$lines.Add('                    "updated_at DATETIME(6) NULL, " +')
$lines.Add('                    "PRIMARY KEY (id)" +')
$lines.Add('                    ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci"')
$lines.Add('                );')
$lines.Add('                log.info("messages 表创建完成");')
$lines.Add('            }')
$lines.Add('        } catch (Exception e) {')
$lines.Add('            log.warn("数据库迁移（messages表）跳过或失败: {}", e.getMessage());')
$lines.Add('        }')
$lines.Add('    }')
$lines.Add('}')

$content = $lines -join "`r`n"
[System.IO.File]::WriteAllText($filePath, $content, [System.Text.UTF8Encoding]::new($false))
Write-Host "文件更新完成"
